### PR TITLE
Configurable bucket for latency metric

### PR DESCRIPTION
**Pull request by Yuras**
See #68

This adds `instrumentHandlerValueWithHistogramAndFilter` which allows to use custom histogram, e.g. specify custom buckets, metric name, names for labels.

### CODE REVIEW

**Comment by jonathanjouty** [comment]
@fimad Thanks for the libraries 🙌🏽 
Is there anything we @scrive can do to help get this change (or an alternative solution for #68) reviewed and released?

**Comment by fimad** [comment]
Looks good to me, sorry this fell off my radar.

**Comment by jonathanjouty** [comment]
Thank you!

**Comment by mniip** [comment]
@fimad Can we get a hackage release with this please?

**Comment by fimad** [comment]
This change was released in version [1.0.1.0](https://hackage.haskell.org/package/wai-middleware-prometheus-1.0.1.0). Is there something missing from that release?

**Comment by mniip** [comment]
My bad... It did indeed. I'm not sure how I missed it.

**Pull request merged**
